### ISSUE TITLE
Align content of footer 

### ISSUE THREAD

**Issue by varsha-saini02** [avinash201199/My-Gallery-4u#116]
![footer_](https://user-images.githubusercontent.com/114968675/194557070-d60be6fe-f609-4fc8-b1c3-4c7eff4f7d5d.png)

Isn't the height of footer is more than it should be?

I would like to align the content more properly and want to update the color of social icons in footer while hovering.

Please assign me this issue.
Thank you

**Comment by JayantDane123** [comment]
Hello sir , 
please assign me for this issues 
I ensure to complete it within stipulated time
