### ISSUE TITLE
Improve README of this Repo

### ISSUE THREAD

**Issue by utkarsh006** [avinash201199/My-Gallery-4u#122]
- Want to improve README of this project.
- This will help users to get better readability about your repo.
- Do consider this issue under hacktoberfest.

**Comment by Aly838** [comment]
Please assign me this issue..I would like to work on it

**Comment by utkarsh006** [comment]
@Aly838  Kindly assign this issue to me since I have opened it.

**Comment by avinash201199** [comment]
you are assigned , will accept your pr first don't worry :)
