### ISSUE TITLE
Grammar Mistakes in Guidelines.md

### ISSUE THREAD

**Issue by dev-32** [avinash201199/My-Gallery-4u#129]
Around 4-5 mistakes or corrections are needed to make Guidelines.MD file is more interactive and error-free.
<img width="770" alt="Screenshot 2022-10-16 at 12 15 31 PM" src="https://user-images.githubusercontent.com/99115141/196022237-c1ada387-4b97-4a94-ab42-a621dcd74b33.png">

**Comment by RishikaKant** [comment]
Please assign me this issue
