### ISSUE TITLE
Add social link in follow instagram section

### ISSUE THREAD

**Issue by GulshanKataria** [avinash201199/My-Gallery-4u#43]
<img width="960" alt="test" src="https://user-images.githubusercontent.com/66901234/136518102-44c29bb5-3fe3-4b2d-80da-01fe6e08e418.PNG">

Follow instagram on author is not redirecting to authors instagram page

**Comment by aarrpitt** [comment]
Hello Sir, please assign me this task.

**Comment by avinash201199** [comment]
> @avinash201199 Kindly assign me this issue

I have assigned you 2 issue already please work on it :)

**Comment by Shiyasmohd** [comment]
I can do it, please assign me

**Comment by avinash201199** [comment]
> I can do it, please assign me

create your own issue ,will assign you :)
