### ISSUE TITLE
Add information to about us page 

### ISSUE THREAD

**Issue by avinash201199** [avinash201199/My-Gallery-4u#58]
![image](https://user-images.githubusercontent.com/61057666/136707430-9c6a9fb3-36c0-4d22-a355-48b84c44d0e1.png)
![image](https://user-images.githubusercontent.com/61057666/136707446-1bc5b3a5-b26a-48f1-b201-4304166f92bc.png)

replace the default text with suitable words related to my page :)

**Comment by SanskritiKhatiyan** [comment]
@avinash201199  Plzz assign this issue to me...I would like to work on it

**Comment by yamini3707** [comment]
Please assign me this. I would like to work on this.

**Comment by Ambareen15** [comment]
can i add the info to the about us?
