### ISSUE TITLE
Enhancing the social media icons

### ISSUE THREAD

**Issue by gaurav879** [avinash201199/My-Gallery-4u#90]
Your website is quite appealing but this part of social media icons can be improved
![image](https://user-images.githubusercontent.com/81583851/138777306-c8589ac5-0d25-40f1-a304-30feec244b9d.png)

small bug which can be eliminated
![image](https://user-images.githubusercontent.com/81583851/138777270-d46520c5-6c33-42e5-ae6b-1080f15f13c4.png)

**Comment by avinash201199** [comment]
> Hey @avinash201199 can u please assign this issue to @kshitij-404 he is my friend and he will resolve it, I am busy with some other stuff.
> 
> Hoping u consider.

Done :)

**Comment by kshitij-404** [comment]
@avinash201199 I have created the PR #100  for fixing this issue, please kindly review.
